### ISSUE TITLE
Performing a search query triggers an “insecure connection” warning in Firefox

### ISSUE THREAD

**Issue by simevidas** [codeforcroatia/popravi-to#163]
1. Open https://popravi.to/ in desktop Firefox
2. Type something into the search box and press Enter

I’m on macOS. Firefox shows me this warning very rarely on other sites, so it’s not a common occurence. Off the top of my head, I can’t think of any other website that has this issue. 

<img width="811" alt="Screenshot 2021-11-02 at 15 38 33" src="https://user-images.githubusercontent.com/716405/139869839-0b19fdf6-f1d4-4d96-b5b6-103ff92f5209.png">

**Comment by simevidas** [comment]
I had to temporarily disable HTTPS-only mode in Firefox to even see the non-HTTPS request in the Network panel, but it’s there, which confirms the bug.

<img width="813" alt="Screenshot 2021-11-02 at 15 48 55" src="https://user-images.githubusercontent.com/716405/139870890-cfab11b8-6946-4bd9-883d-cdd9c66ae4fd.png">

**Comment by schlos** [comment]
I can confirm the same problem on Brave browser:
![Screenshot from 2021-11-02 15-55-06](https://user-images.githubusercontent.com/1014134/139872747-a816efea-2bad-4bd2-9914-1ae3f34454a0.png)

Related to this, GH issue upstream: https://github.com/mysociety/fixmystreet/issues/2814
And discussion on a mailing list: https://groups.google.com/a/mysociety.org/g/fixmystreet/c/4Xt21ZL3OhM

**Comment by schlos** [comment]
I fixed it by adding the following in the `@catalyst` section in NGINX config:

```
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Host $host;
```

@simevidas Thank you for reporting the error! Please check if it's working now on your end.
