### ISSUE TITLE
Menu cannot be closed if opened on mobile

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/popravi-to#174]
**Describe the bug**

Mobile menu was broken when fixing desktop menu position (see #103).
Menu cannot be closed if opened on mobile.

**To Reproduce**

**Expected behavior**

Menu should be displayed below menu hamburger icon. Menu should be possible to close by clicking on hamburger icon.
By fixing this we should not revert fix made for desktop: #103.

**Screenshots**

![photo_2021-11-11_22-22-26](https://user-images.githubusercontent.com/1014134/141370939-599c48a6-bda5-4f8c-8d46-48a0120b4111.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by schlos** [comment]
**How to contribute?**
Read our contribution guidelines at https://codeforcroatia.org/popravito-contribution-guidelines.

**Comment by znmustic** [comment]
Preuzela i ovo :)

**Comment by schlos** [comment]
Test report:

- before pull request #192

![photo_2023-06-12_10-10-06](https://github.com/codeforcroatia/popravi.to/assets/1014134/790fbe32-f782-4f1d-97ca-66345b5603b2)

![photo_2023-06-12_10-10-02](https://github.com/codeforcroatia/popravi.to/assets/1014134/a554d2af-f16d-43f1-819e-b3ecf6fe4cfa)


- after pull request #192

![photo_2023-06-12_10-11-21](https://github.com/codeforcroatia/popravi.to/assets/1014134/30aead39-2291-435a-a5be-fe2eed1ebdbf)

![photo_2023-06-12_10-11-18](https://github.com/codeforcroatia/popravi.to/assets/1014134/25b61be5-016a-4d06-9738-eed1c94feee0)

![photo_2023-06-12_10-12-54](https://github.com/codeforcroatia/popravi.to/assets/1014134/df817c73-79aa-498e-afaa-09e918784979)


Menu icon is now moved outside of the screen, although issue is fixed and menu button is visible when menu is opened, and can be closed by clicking the menu icon again.

@znmustic, fix for this would be to move menu position back to the visible part of the screen (top right part of the mobile screen). How does that sound?

An improvement, if possible would be to show "X" instead of the menu hamburger icon for the menu close action. I.e. X button would be as big as hamburger icon. Let us know if you need a Figma design for this, and we will ask designer to take a look.

**Comment by znmustic** [comment]
I did what you asked, I think that now is all good. Just made a pull for fix https://github.com/codeforcroatia/popravi.to/pull/194 so you can check it and tell if needed anything more.

**Comment by schlos** [comment]
Fixed via #194 

Screenshots after the fix:

![photo_2023-06-13_16-08-19](https://github.com/codeforcroatia/popravi.to/assets/1014134/96ad7888-7a7d-49a9-bc8f-80f0b3254d5f)
![photo_2023-06-13_16-08-16](https://github.com/codeforcroatia/popravi.to/assets/1014134/792e7e98-0cea-460c-bafc-ebd34d50e843)
