### ISSUE TITLE
Update link/button is not visible on report page

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/popravi-to#178]
**Describe the bug**

When viewing a report (report details page), update button ("Ažuriraj") is not visible.

For comparison:
Update button ("Ažuriraj") is visible if there are already other updates/comments added.

**To Reproduce**

**Expected behavior**

As per figma.

**Screenshots**

Current - report without comments - missing Update / "Ažuriraj" button:

![Screenshot from 2021-11-24 11-46-11](https://user-images.githubusercontent.com/1014134/143224485-c5386598-8a94-4a45-95e1-96425c3b34a1.png)

Current - for comparison - report with comments - Update / "Ažuriraj" button is visible:

![Screenshot from 2021-11-24 11-45-50](https://user-images.githubusercontent.com/1014134/143224528-72cc3a12-fe9f-4ef9-b036-104dc4b130b7.png)

Expected (Figma design):

https://www.figma.com/proto/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=3148%3A11297&scaling=min-zoom&page-id=25%3A186&hide-ui=1

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by schlos** [comment]
**How to contribute?**
Read our contribution guidelines at https://codeforcroatia.org/popravito-contribution-guidelines.

**Comment by schlos** [comment]
Temporary fixed by adding button next to the Title.

**Comment by znmustic** [comment]
@schlos  ovo preuzimam :)

**Comment by schlos** [comment]
Fixed with the pull request #192.

- added "provide an update" form below the report

![Screenshot from 2023-06-12 09-46-06](https://github.com/codeforcroatia/popravi.to/assets/1014134/432b696b-2b04-4710-8289-d606819c7e18)

![Screenshot from 2023-06-12 09-46-37](https://github.com/codeforcroatia/popravi.to/assets/1014134/0e68a35f-e4e9-4933-a622-52bbc902d94f)

![Screenshot from 2023-06-12 10-22-28](https://github.com/codeforcroatia/popravi.to/assets/1014134/59b64853-3cab-4c17-b726-3d3584d0dd44)

![Screenshot from 2023-06-12 10-22-15](https://github.com/codeforcroatia/popravi.to/assets/1014134/1d321e3f-a9e5-4572-a9c2-951594615481)


- for comparison, our current production theme shows the same update form:

![Screenshot from 2023-06-12 10-23-42](https://github.com/codeforcroatia/popravi.to/assets/1014134/274f8ac8-9cb4-46ca-a0c5-2cb84c405dd5)
