### ISSUE TITLE
Email designs for Popravi.to

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/popravi-to#28]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is; e.g. I'm always frustrated when [...]

**Describe the solution you'd like**

Email design should follow same design as done in Figma for Website design for Popravi.to #5.

**Describe alternatives you've considered**

**Additional context**

Internal folder with email screenshots - examples from other web templates:
https://drive.google.com/drive/u/0/folders/1ZhdzMEwDXtx61Cj6pMp50fqxAqo5kPl5

**Comment by not-alpha** [comment]
Emails based on provided screenshots:
https://www.figma.com/file/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=2583%3A11461

@schlos

**Comment by schlos** [comment]
Thanks, looks awesome!
I have added few comments and suggestions in Figma. @not-alpha

**Comment by schlos** [comment]
Email templates:
1. Confirm email: https://www.figma.com/proto/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=2583%3A11461&scaling=min-zoom&page-id=2583%3A9884&hide-ui=1
2. New reports (with thumbnails): https://www.figma.com/proto/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=2583%3A11837&scaling=min-zoom&page-id=2583%3A9884&hide-ui=1
3. New reports (no thumbnail): https://www.figma.com/proto/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=2583%3A11531&scaling=min-zoom&page-id=2583%3A9884&hide-ui=1
4. Confirm update: https://www.figma.com/proto/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=2583%3A11614&scaling=min-zoom&page-id=2583%3A9884&hide-ui=1
5. Report is recorded: https://www.figma.com/proto/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=2583%3A11962&scaling=min-zoom&page-id=2583%3A9884&hide-ui=1
6. Questionnaire: https://www.figma.com/proto/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=2583%3A12081&scaling=min-zoom&page-id=2583%3A9884&hide-ui=1
7. Report to authority: https://www.figma.com/proto/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=2593%3A9948&scaling=min-zoom&page-id=2583%3A9884&hide-ui=1
