### ISSUE TITLE
2fa - two-factor authentication screens for Popravi.to

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/popravi-to#33]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is; e.g. I'm always frustrated when [...]

**Describe the solution you'd like**

Screens missing from original Popravi.to Figma designs are related to two-factor authentication (2fa):
https://github.com/codeforcroatia/popravi.to/tree/develop/templates/web/base/auth/2fa

**Describe alternatives you've considered**

**Additional context**

https://snippyly.com/img/?q=j0mZoO20raWdERJrTAHV (&EDIT=wguJjUHCxbD2iCvB5WI2)
https://snippyly.com/img/?q=Jot1xGfArYZFTaT3f7RE (&EDIT=NELSmJvL19xjKkL7A5NL)
https://snippyly.com/img/?q=8bGMVnTdTybyAo5cjiH7 (&EDIT=wflSz0bVnS35nRzA2pAX)
https://snippyly.com/img/?q=fk2Ml8SRGzVJRPtGgtMU (&EDIT=t22tPZk2DdSEa74O7jiz)
https://snippyly.com/?q=l70Qe8U2kgLfwOu7sVko (&EDIT=SD7bV4ZlHnZzD6tm1yKQ)

![screencapture-beta-test-popravi-to-auth-generate-token-2021-08-09-16_10_19](https://user-images.githubusercontent.com/1014134/128720384-486c793f-07f6-4c24-8bbd-215a8546776f.png)

**Comment by schlos** [comment]
User story za 2fa - kako dodje do 2fa:

- kada user otvori Profile page (/my), vidi link "Security"
- kada otvori Security stranicu, vidi screenove koji su prikazani u descriptionu ticketa

**Comment by not-alpha** [comment]
@schlos evo ekrana za admin - security: https://www.figma.com/file/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=2750%3A10295

Javi ako misliš da nešto ne funkcionira

**Comment by schlos** [comment]
@not-alpha ostavio sam par komentara u Figmi.

**Comment by schlos** [comment]
Design is done.
