### ISSUE TITLE
Popravi.to OpenGraph image

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/popravi-to#40]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

When sharing Popravi.to links, OpenGraph image will be shown in places where problem image is not available. This is bigger image than logo that visually represent a product or a website.

**Describe alternatives you've considered**

**Additional context**

Default example from FixMyStreet design is:
http://beta.test.popravi.to/cobrands/fixmystreet/images/fms-og_image.jpg

**Comment by not-alpha** [comment]
@schlos 
Couldn't find a better mockup so I just photoshoped our app instead of fms. If I come up with something better we can change it later

![popravi-og](https://user-images.githubusercontent.com/952710/135754352-58a8c6be-5c0f-4e08-9b9f-f03c2dd3b464.jpg)

**Comment by schlos** [comment]
Thanks! This is good enough!
We could later take photo with somebody holding the phone, and then take it from there.
