### ISSUE TITLE
Website design for Popravi.to

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/popravi-to#5]
**Is your feature request related to a problem? Please describe.**

Precondition is:
- Logo design Popravi.to help wanted #3 

**Describe the solution you'd like**

Website design for Popravi.to. For inspiration see resources below.

See theme assets for fixmystreet.com:
- https://github.com/codeforcroatia/popravi.to/tree/master/web/cobrands/fixmystreet
- https://github.com/codeforcroatia/popravi.to/tree/master/web/cobrands/fixmystreet.com

See template assets for fixmystreet.com:
- https://github.com/codeforcroatia/popravi.to/tree/master/templates/web/fixmystreet.com
- https://github.com/codeforcroatia/popravi.to/tree/master/templates/email/fixmystreet.com

**Describe alternatives you've considered**

Quick and dirty solution: 
- Alternatively use fixmystreet assets with changed color schemes.

**Additional context**

Base design wireframes on fixmystreet, update color schemes and items to be aligned with Code for Croatia brand or see example at imamopravoznati.org. Or take it freestyle and make new web design from scratch for all pages as listed in fixmystreet assets (see links above).

Screenshots of all designs in 'cobrands': https://drive.google.com/drive/folders/15BNzV_j_FGysFz2bTXu0JUue2uq8kzWo?usp=sharing

FixMyStreet documentation: **[Customising the design](https://fixmystreet.org/customising/css/)**

How to change the colour scheme?
See [changing colour and CSS](https://fixmystreet.org/customising/css/) for detailed instructions.
You can just change the colour variables without needing to touch any other CSS.

**Comment by not-alpha** [comment]
- [x] Login
- [x] Homepage
- [x] Report a problem
- [x] All reports
- [x] Local alerts
- [x] My profile
- [x] Help
- [x] Privacy
- [x] Contact
- [x] Promotion

**Comment by schlos** [comment]
Next on the list:
- Email designs (HTML) --> #28
- Admin pages --> #29

**Comment by schlos** [comment]
Closing this as we're done with initial Figma design. See linked issues for the next steps.
