### ISSUE TITLE
popravitobase: Top menu issues - dark 'Report an problem' and underlined current page

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/popravi-to#53]
**Describe the bug**

Top menu issues:
- missing dark 'Report an problem'
- missing underlined current page.

**To Reproduce**

**Expected behavior**

Top menu:
- has always dark 'Report an problem' link
- has underlined only current page

**Screenshots**

Current problem (web cobrand "popravitobase"):
https://snippyly.com/img/?q=IcfyOBkjZKOeaogTDXlY (&EDIT=4EnVF8bPhWFmjgV0sA9d)

Expected (as per Figma design):
https://snippyly.com/img/?q=hgmv3W0jXMjQkVaE7lYQ (&EDIT=WZKXfYIapY79qY6q9g8J)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by schlos** [comment]
@not-alpha is my understanding of Figma design correct that underlined link in top menu is always showing only current page?

**Comment by not-alpha** [comment]
> @not-alpha is my understanding of Figma design correct that underlined link in top menu is always showing only current page?

Yes, the underlined link in top menu is an indicator of the current page

**Comment by schlos** [comment]
Kostya feedback:
Cant make to underline each page, because they did smth wrong and I cant attach to some attributes in HTML and in HTML is generated and cant add classes

**Comment by schlos** [comment]
@not-alpha could you check if it's acceptable to change design requirements to go without underlined current page?
@barbaraperic @reine93 could you review this and give your feedback? Do you see this as easily fixable?

**Comment by not-alpha** [comment]
We can go without underline under current page but we need some indicator. If underline is not possible we can change text color of the menu item for current page to orange

**Comment by kostyakazmiruk** [comment]
There is no problem to make underline text or make it become orangem, that's the structure. For example, when I am on Local Alerts page in nav local alerts are span element, but sometimes its li

**Comment by schlos** [comment]
Not fixed:
https://snippyly.com/img/?q=qP2oJSl0LW0xFIpSuTUw &EDIT=U2vLQtauO7Q5XfMvuC0Z

Expected:
as per [Figma](https://www.figma.com/proto/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=543%3A5651&scaling=min-zoom&page-id=543%3A5650&hide-ui=1) + effect on mouse hover (underline or alternatively change text color)

@Green8888Elephant, our developer confirmed it should not pose a problem to fix this, but if you have again question - let us know and we will work it out
