### ISSUE TITLE
popravitobase: All reports dashboard page layout and font issues

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/popravi-to#54]
**Describe the bug**

Issues found on 'All reports' dashboard page:
- in general: fonts issue
- title is not expected to be there
- 'Show reports in your area' box wrong location
- search box inside 'Show reports in your area' box is missing icon (magnifying glass) and label in search box is missing
- 'All time' report statistics above graph has layout issue
- 'Last 7 days' statistics is in wrong location

**To Reproduce**

**Expected behavior**

Fixes as per [Figma design](https://www.figma.com/proto/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=543%3A6717&scaling=min-zoom&page-id=543%3A5650&hide-ui=1).

Issues found on 'All reports' dashboard page:
- in general: fix fonts issue (font style should be as from Figma)
- title 'Dashboard' can be hidden (comment out form the code)
- move 'Show reports in your area' box to correct location (see as marked on the screenshots, as per Figma)
- add icon (magnifying glass) and label in the search text box on 'Show reports in your area'
- fix layout on 'All time' report statistics above graph (to match Figma)
- move 'Last 7 days' statistics to the right hand side from graph

**Screenshots**

Current problem ('popravitobeta' cobrand):
https://snippyly.com/img/?q=m6mngUUR7HmzoCGS2gF8 (&EDIT=MVfKGwI0dUWl4hfDsmBi)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by schlos** [comment]
Kostya feedback:
With structure of files i cant make it like in Figma (I cant fix it)

**Comment by schlos** [comment]
@not-alpha could you check if we can change design requirements to fit what is possible to achieve by Kostya?
@barbaraperic @reine93 could you review this and give your feedback? Do you see this as easily fixable?

**Comment by not-alpha** [comment]
> Kostya feedback:
> With structure of files i cant make it like in Figma (I cant fix it)

Please ask Kostya to provide more detailed feedback and specify what is causing problem so we can come up with a workaround

**Comment by kostyakazmiruk** [comment]
![image](https://user-images.githubusercontent.com/53175180/128904295-dc13448d-ffb1-4bb9-82e5-42562d076d91.png)
Because they are in different dashboard-rows I cant wrap them add grid and make it like in Figma

**Comment by schlos** [comment]
This is I think more question for developers - @barbaraperic @reine93 can you take a look?

**Comment by schlos** [comment]
Hi Kostya @Green8888Elephant 

Here is feedback I received from @barbaraperic 

> Hey Kostya,
> 
> I would suggest you try the following:
> 1. To move the Show report in your area card to the top => grab the <div class='dashboard-item dashboard-item--6' ></div> [1. screenshot], containing the form with <form class='dashboard-search'></form> and move that div just below the <div class='dashboard-header'></div> .
> 
> 2. To display the Canvas next to the Last 7 days [2. screenshot] => wrap the <div class="dashboard-item dashboard-item--12"></div> and <div class="dashboard-item dashboard-item--6"></div> in the <div class="dashboard-row"></div> and give the parent div (the one with the class dashboard-row) a css style rule display: flex;
> 
> Let me know if you have any questions or if I can explain it in a better way
> 
> ![1  Screenshot](https://user-images.githubusercontent.com/1014134/131550186-e0602a7c-22bd-4b62-960c-b16b7aaaadfc.png)
> 
> ![2  Screenshott](https://user-images.githubusercontent.com/1014134/131550197-aa113b77-a153-43e7-91e4-ca21336f49d9.png)
