### ISSUE TITLE
popravitobase: Local alerts page layout and font issues

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/popravi-to#55]
**Describe the bug**

Local alerts page issues:
- in general: layout is wrong (width of page content)
- in general: font styling is wrong
- location search box is missing symbol and label inside the text box
- Automatic geolocation text below search box is missing symbol and has wrong styling
- Space between page content and footer is to small
- unexpected part with reports photos is displayed

**To Reproduce**

**Expected behavior**

As per [Figma design](https://www.figma.com/proto/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=543%3A6886&scaling=min-zoom&page-id=543%3A5650&hide-ui=1).

Local alerts page fixes:
- in general: fix layout to match Figma (e.g. width of page content)
- in general: fix font styling to match Figma
- add magnifying glass symbol and move label from top to inside the text box for location search box
- add pin symbol in the Automatic geolocation text below search box and fix styling
- add space between page content and footer
- hide (comment out in the code) part with reports photos

**Screenshots**

Current problem ('popravitobase' cobrand):
https://snippyly.com/img/?q=Dh7bdfBee4rtwwxSp0JX (&EDIT=H99TqfwhtmIyXAItwWrJ)

Expected (as per Figma designs):
https://snippyly.com/img/?q=GB2BrwwnagVEs7sIVLG2 (&EDIT=8XcKu1XfjUVDBrqMVVmq)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by schlos** [comment]
Kostya feedback:
cant make label and icon in the input

**Comment by schlos** [comment]
@not-alpha could you check this to change design if current is not achievable by developer?
@barbaraperic @reine93 could you review this and give your feedback? Do you see this as easily fixable?

**Comment by not-alpha** [comment]
If having both icon and label inside input field is problem we can keep just label.

**Comment by schlos** [comment]
@Green8888Elephant please take a look at last comment from Elizabeta. Can you do it like she suggested?

**Comment by schlos** [comment]
Still not fixed.
