### ISSUE TITLE
popravitobase: Margins not as expected

### ISSUE THREAD

**Issue by not-alpha** [codeforcroatia/popravi-to#58]
**Describe the bug**
- Left and right margins are too wide (marked red on the photo below)
- Padding between top menu and title is too small (marked orange on the photo below)

**Expected behavior**
Left and right margins should be 120px on all pages ([Figma](https://www.figma.com/proto/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=543%3A5651&scaling=min-zoom&page-id=543%3A5650&hide-ui=1))

**Screenshots**
![Home](https://user-images.githubusercontent.com/952710/127748156-71779031-bb0e-473f-9ef2-fcf100d6d929.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox

**Comment by schlos** [comment]
Not fixed yet.
