### ISSUE TITLE
popravito: Homepage header - menu padding too big (🅼3)

### ISSUE THREAD

**Issue by not-alpha** [codeforcroatia/popravi-to#59]
**Describe the bug**
Paddinzi u meniju su preveliki 

**Expected behavior**
Za top menu:
Font size = 14px
Padding unutar svakog od menu itema je 8px s lijeve/desne strane
Razmaci između njih su 24px

Primjer u Figmi: https://www.figma.com/file/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=1909%3A9398

**Screenshots**
<img width="1280" alt="Screenshot 2021-07-31 at 20 22 06" src="https://user-images.githubusercontent.com/952710/127749146-fc1d52be-c169-46a3-b794-6eb070add7e7.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox

**Comment by schlos** [comment]
This is marked as fixed by Silvija in PR #81 & #91
@not-alpha can you take a look and verify fix on our test URL?

**Comment by not-alpha** [comment]
This issue (paddings between menu items) has been fixed but I think that something got messed up in the process. The menu items are not centered in relation to the logo (image below)

<img width="1280" alt="Screenshot 2021-08-26 at 18 00 05" src="https://user-images.githubusercontent.com/952710/130997153-28e8f9ee-7dad-4aac-8237-8fc9078aed76.png">

**Comment by schlos** [comment]
Issue is fixed as per @not-alpha comment:
> This issue (paddings between menu items) has been fixed but I think that something got messed up in the process. 

New bug that @not-alpha found will be tracked in #103
