### ISSUE TITLE
popravito: Homepage - circles not perfect (🅼3)

### ISSUE THREAD

**Issue by not-alpha** [codeforcroatia/popravi-to#61]
**Describe the bug**
Circle shapes are not perfect circles

**Screenshots**
<img width="1280" alt="Screenshot 2021-07-31 at 20 29 21" src="https://user-images.githubusercontent.com/952710/127749483-b25febde-d468-4312-aedc-fa55e8f7aec1.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox

**Comment by schlos** [comment]
@not-alpha this is marked as fixed by Silvija in PR 91. Can you take a look and add your findings here?

I can still see it's reproducible, for example:
https://snippyly.com/img/?q=5BX5vcb14uQplXr9HLeS (&EDIT=u7TRfGBaGRGYRVcGnJmy)

@SilvijaProzinger could you take a look this issue I found - can you reproduce it on your end?

**Comment by schlos** [comment]
Feedback Silvije:

Što se tiče buga #61, mislim da bi gumb za pretraživanje sad (nakon sljedeceg PR-a) trebao biti ok jer sam primjenila iste dimenzije i border radius kao u dizajnu, a što se tiče ovih krugova s brojevima nisu ni u dizajnu baš krugovi već više elipse budući da su brojevi "dugoljasti" pa ako budem primjenila padding koji bi ih oblikovao da bude bliže pravom krugu bit će preširoki. Svejedno ću se probati poigravati s time da ih malo bolje oblikujem, jer ih je primjenjivanje paddinga u dizajnu učinilo preširokima.

**Comment by schlos** [comment]
Marked circles from original description looks fixed (> and 1), but I think that 2, 3, 4 circles are a bit oval.

I will create new task to try to solve this in another manner --> #94

@not-alpha please retest this and comment here your test findings for reported items: (>) and (1)
