### ISSUE TITLE
Design for a questionnaire page

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/popravi-to#77]
**Is your feature request related to a problem? Please describe.**

Current questionnaire page on 'popravito' cobrand looks wrong:
http://dev.test.popravi.to/Q/ALAZbrEUZFNiD32pgA?been_fixed=No

**Describe the solution you'd like**

As per other cobrands.

**Describe alternatives you've considered**

**Additional context**

Example of questionnaire page:
![screencapture-beta-test-popravi-to-Q-ALAZbrEUZFNiD32pgA-2021-08-09-12_28_43](https://user-images.githubusercontent.com/1014134/128693311-a767858f-1c10-485b-b207-83c5a4db7500.png)

Confirmation after submitting (//questionnaire/submit):
https://snippyly.com/img/?q=2D2cSZZ0jcStEPrrGVWw (&EDIT=GroUAIqj8hZE5uNbDuIt)

**Comment by not-alpha** [comment]
@schlos here is the design for the questionnaire page - https://www.figma.com/file/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=2554%3A10305

I thought that maybe it would be better if we give some context first (which problem) and then ask all the questions. I'm open to your feedback, let me know if we need to change something

**Comment by schlos** [comment]
Looks good to me. Thanks!

Desktop: https://www.figma.com/proto/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=2554%3A10305&scaling=min-zoom&page-id=25%3A186&hide-ui=1
Mobile: https://www.figma.com/proto/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=2556%3A9929&scaling=min-zoom&page-id=25%3A186&hide-ui=1

Marking as done.

**Comment by schlos** [comment]
One fix to do:
Allign questionnaire page button design for Fixed, Not fixed, Don't know with button design in the questionnaire reminder email.
