### ISSUE TITLE
Add LinkedIn icon in the footer

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/popravi-to#84]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Add LinkedIn icon in the footer.
https://www.linkedin.com/showcase/popravi.to

**Describe alternatives you've considered**

**Additional context**

**Comment by schlos** [comment]
**How to contribute?**
Read our contribution guidelines at https://codeforcroatia.org/popravito-contribution-guidelines.

**Comment by not-alpha** [comment]
@schlos added!

https://www.figma.com/file/OrvZfg5BsfdOzeL7nhRpEI/Popravi.to?node-id=464%3A4549

**Comment by schlos** [comment]
Thank you @not-alpha.

There is more work: we need help of a frendly frontend developer who can make this change in footer html:
https://github.com/codeforcroatia/popravi.to/blob/develop/templates/web/popravitodev/footer.html#L53

**Comment by schlos** [comment]
Worked by @znmustic

**Comment by schlos** [comment]
Done:

![Screenshot from 2023-06-12 10-01-24](https://github.com/codeforcroatia/popravi.to/assets/1014134/b6adc999-659f-47e9-8328-ab201aa9efbc)
